name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: build and push to docker
        - uses: actions/checkout@v4
        - name: Login Docker
          env:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
        - name: Build Docker Image
          run: docker build -t menuqr .
        - name: Push to Docker
          run: docker push leovildoza/menuqr:latest
