name: Build and Deploy BackendApp Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    - name: Login to GitHub Container Registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the MenuQR Docker image
      run: docker build . --tag menuqr.io/leovildoza/menuqr:latest
    - name: Push the MenuQR Docker image
      run: docker push menuqr.io/leovildoza/menuqr:latest
