name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    build:

        name: build to image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Login Docker
          env:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        - name: Build the Docker image
          run: docker build -t menuqr .

        - name: Push the Docker image
          run: docker push leovildoza/menuqr:latest
